# Setup
title:               Blog
tagline:             'A simple blog based on Jekyll'
description:         ''
url:                 https://liyinsg.github.io
paginate:            20
gems:                [jekyll-paginate]

# Custom vars
version:             1.0.0
